- id: doi:10.1182/blood.2021014205
  image: https://ash.silverchair-cdn.com/ash/content_public/journal/blood/139/14/10.1182_blood.2021014205/7/m_bloodbld2021014205absf1.png?Expires=1714478557&Signature=wuoLwox09RXiKkDNZn6uvPlZcCEHoGm7o60SfGgmhFSbPgTu5Knc~-X6CcIVasTjoX2uX2D4KEMyucIKs8ARpce685IX4HuGfGEftL3~tL1NYiYWzwxR9IPLdgo1LnZ0Fu20ojGwoFoaziHNx8-EqWIXxLvqh1BJmvd0neLwBBKe8Ap7tqQrg4GRKfeHPvTAlQNAe4w4EHkgD1-dxHgyVKCIjnTilsyKyAH1G6rC4GkYAocKfFGfrk~hPRmoYiJONGrA119NOrtacTzxG~Ope6qvcKspfQEdzndpFpND1SWAHB3ozLavR5AGSct8aGhHneFJhA5PtSRcpY-OMQFQ-Q__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
- id: doi:10.1016/j.ymthe.2024.01.023
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1525001624000236-fx1.jpg
- id: doi:10.1038/s41588-023-01434-7
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41588-023-01434-7/MediaObjects/41588_2023_1434_Fig3_HTML.png?as=webp
- id: doi:10.1038/s41588-022-01152-6
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41588-022-01152-6/MediaObjects/41588_2022_1152_Fig6_HTML.png?as=webp
- id: doi:10.7554/elife.65421
  image: https://iiif.elifesciences.org/lax/65421%2Felife-65421-fig5-v2.tif/full/1234,/0/default.webp
- id: doi:10.1016/j.tig.2022.07.003
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9837857/bin/nihms-1828329-f0001.jpg
- id: doi:10.1016/j.omtn.2023.09.002
  image: https://www.cell.com/cms/attachment/e0494638-0fb5-4240-81c0-848de09822e2/fx1.jpg
- id: doi:10.1038/s41467-020-16388-1
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-020-16388-1/MediaObjects/41467_2020_16388_Fig6_HTML.png?as=webp
- id: doi:10.1002/bies.201900041
  image: https://onlinelibrary.wiley.com/cms/asset/ed179679-453a-4b2e-a162-e97f97a104ae/bies201900041-fig-0001-m.jpg
  id: doi:10.1038/s41467-025-62177-z
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-025-62177-z/MediaObjects/41467_2025_62177_Fig7_HTML.png?as=webp
  id: doi:10.2139/ssrn.4988511
  image: https://www.cell.com/cms/10.1016/j.celrep.2025.115518/asset/af15daaf-f7eb-466c-97e5-d18d5c5c40d1/main.assets/fx1.jpg
  id: doi:10.1093/jleuko/qiac009
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/jleukbio/113/2/10.1093_jleuko_qiac009/1/m_qiac009f2.jpeg?Expires=1756154820&Signature=Fq0qGPd91w6dJo9CEyhmF91cc3G2cnmUkvg6kHxZDmLOONkLbRlZChWMA7E5TojHdCAhVz1V0ZhIXH9vz5icqSkreGEQWFpv-2SQiIahEzS3aXeavzz0ELijJIln3crPJmR1bqMNWoIMcxHiAa8mZ9DAIbFRc16Hr~X8TOFreYjTV8g6klHl8XMF0ZyWYyzdEk0BKMRufA0Z0UsItEpncHhohLc8yNmpHQ-XeN1OuB7TOMRafclNw9-1x-WZe-dOYTf3q5SgR3TDCIp2qNUXYKI3PgkGAYhHtmJOTrA7fXZKy75sJ-0uJDFfOVj5AOhXsJl-iTZFqc81meSEs-AW2A__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA